workload:
  kind: DaemonSet

image:
  registry: docker.io
  repository: phongleduc/notification-api
  tag: latest
  pullPolicy: Always

replicaCount: 3

# Thêm các tùy chỉnh tên
nameOverride: "dotnet-core-api"
fullnameOverride: "notification-api-service"

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  name: notification-api-service 

# Tên deployment tùy chỉnh
deployment:
  name: notification-api-deployment

# Annotations để force redeploy
podAnnotations: {}

# Tên ingress tùy chỉnh
ingress:
  enabled: true
  name: notification-api-ingress
  ingressClassName: nginx
  hostname: notification-api.cuder.xyz
  path: /
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # Thêm annotation để xử lý path của Swagger UI
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  tls: true
  extraTls:
    - hosts:
        - notification-api.cuder.xyz
      secretName: notification-api-tls

containerPorts:
  http: 8080

# Môi trường từ Secret
extraEnvVarsFromSecret:
  - secretName: notification-api-secret
    name: ConnectionStrings__DefaultConnection
    envVar: ConnectionStrings__DefaultConnection
    
  - secretName: shared-secret
    name: SmtpMail__UserName
    envVar: SmtpMail__UserName

  - secretName: shared-secret
    name: SmtpMail__Password
    envVar: SmtpMail__Password
    
  - secretName: shared-secret
    name: SmtpMail__Host
    envVar: SmtpMail__Host

  - secretName: shared-secret
    name: SmtpMail__Port
    envVar: SmtpMail__Port

  - secretName: shared-secret
    name: SmtpMail__FromEmail
    envVar: SmtpMail__FromEmail

  - secretName: shared-secret
    name: SmtpMail__FromName
    envVar: SmtpMail__FromName

  - secretName: shared-secret
    name: SmtpMail__SenderEmail
    envVar: SmtpMail__SenderEmail

  - secretName: shared-secret
    name: Redis__Host
    envVar: Redis__Host

  - secretName: shared-secret
    name: Redis__Port
    envVar: Redis__Port

  - secretName: shared-secret
    name: Redis__Password
    envVar: Redis__Password

# Môi trường từ ConfigMap
extraEnvVarsFromConfigMap:
  - configMapName: shared-config
    name: Logging__LogLevel__Default
    envVar: Logging__LogLevel__Default

  - configMapName: shared-config
    name: Logging__LogLevel__Microsoft.AspNetCore
    envVar: Logging__LogLevel__Microsoft.AspNetCore

# Biến môi trường cố định
extraEnvVars:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Production"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi